name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Push to gh-pages      
      run: |
        git config --global user.email danieldoblado@gmail.com
        git config --global user.name "Daniel Doblado"
        git clone --depth 1 https://github.com/dobladov/last-time.git
        cd last-time
        npm install
        npm i -g gh-pages
        parcel build --public-url '/last-lime' src/index.html
        gh-pages -d dist
      
